# Generated by Django 5.1.2 on 2024-10-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
